apiVersion: apps/v1
kind: Deployment
metadata:
  name: esditepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esditepo
  template:
    metadata:
      labels:
        app: esditepo
    spec:
      containers:
      - image: okteto.dev/esditepo:latest
        name: esditepo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "6a745ea0-4dea-49c4-adcc-00e53c601582"
        - name: Vless_Path
          value: "/6a745ea0-4dea-49c4-adcc-00e53c601582-vless"
        - name: Vmess_UUID
          value: "283bf52e-0041-48bd-a2cb-7b0da1de659f"
        - name: Vmess_Path
          value: "/283bf52e-0041-48bd-a2cb-7b0da1de659f-vmess"
        - name: Share_Path
          value: "$Share_Path"
