apiVersion: v1
kind: afwsdeev
metadata:
  name: afwsdeev
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "afwsdeev"
    port: 8080
  selector:
    app: seiodck
